apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./../../base
  - configmap.yaml
  
images:
  - name: test-placeholder
    newName: public.ecr.aws/nginx/nginx
    newTag: 1.26.0-alpine3.19

# replacements:
#   - path: replacement.yaml
  
nameSuffix: -prod