apiVersion: v1
data:
  job_version: test-job-name-with-replacement
kind: ConfigMap
metadata:
  name: demo-a-cm-prod
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-prod
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - image: public.ecr.aws/nginx/nginx:1.26.0-alpine3.19
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: http
      initContainers:
      - command:
        - date
        image: busybox:1.28
        name: print-timestamp
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-options: Replace=true, Force=true
    argocd.argoproj.io/sync-wave: "-1"
  name: test-job-name-with-replacement
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - args:
        - -c
        - date
        command:
        - /bin/sh
        image: public.ecr.aws/nginx/nginx:1.26.0-alpine3.19
        name: print
      restartPolicy: Never
  ttlSecondsAfterFinished: 300
