apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
  spec:
    containers:
    - name: nginx
      image: test-placeholder
      ports:
      - name: http
        containerPort: 80
      imagePullPolicy: IfNotPresent
      