apiVersion: batch/v1
kind: Job
metadata:
  generateName: test-job-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    # notifications.argoproj.io/subscribe.on-sync-succeeded.slack: e-chef-pipeline
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: print
        image: test-placeholder
        command: ["/bin/sh"]
        args: ["-c", "date"]
      restartPolicy: Never
      