apiVersion: batch/v1
kind: Job
metadata:
  name: print
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: print
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "echo Kubernetes Job"]
      restartPolicy: Never