apiVersion: batch/v1
kind: Job
metadata:
  name: print
  annotations:
    argocd.argoproj.io/hook: PreSync
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: e-chef-pipeline
spec:
  template:
    spec:
      containers:
      - name: print
        image: test-placeholder
        command: ["/bin/sh"]
        args: ["-c", "date"]
      restartPolicy: Never