apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-name
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-options: Replace=true, Force=true
    # argocd.argoproj.io/hook: PostSync, SyncFail
    # argocd.argoproj.io/hook-delete-policy: HookFailed, HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
    # notifications.argoproj.io/subscribe.on-sync-succeeded.slack: e-chef-pipeline
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: print
        image: test-placeholder
        command: ["/bin/sh"]
        args: ["-c", "date"]
      restartPolicy: Never
      