apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  
images:
  - name: test-placeholder
    newName: public.ecr.aws/nginx/nginx
    newTag: 1-alpine3.19

nameSuffix: -dev